Financial Report
hpearl725/SFWE_403_TEAM_1 pull request #23
Opened 2023-11-08 01:25 UTC by rsfutch77

2023-11-08 02:15 UTC, hpearl725 requested changes

2023-11-08 02:15 UTC, hpearl725 commented on GUI/prescriptions_table.py
>          return
When medication is not in inventory it errors out, still works but an error is thrown.
<img width="925" alt="image" src="https://github.com/hpearl725/SFWE_403_TEAM_1/assets/64181261/2ff62977-aaba-4251-9be0-a15e058ead1d">

2023-11-08 04:51 UTC, rsfutch77 commented on GUI/prescriptions_table.py
>          return
Fixed here: 96edf12a27ce46ea3f921907c28c990dcc78b19c

2023-11-09 02:23 UTC, hpearl725 approved these changes

2023-11-09 02:24 UTC, merged